### ISSUE TITLE
Invalid entrypoint on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [conda-forge/scalene-feedstock#29]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

On Windows, the entrypoint appears to hard-code the path the the Python interpreter in the CI:
```
❯ scalene --help
Fatal error in launcher: Unable to create process using '"D:\bld\scalene_1689719293639\_h_env\python.exe"  "C:\conda\envs\dev-py310\Scripts\scalene.exe" --help': The system cannot find the file specified.
```

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by dhirschfeld** [comment]
It appears that the entry point isn't specified in the `meta.yaml`:
https://github.com/conda-forge/scalene-feedstock/blob/486a7ec96545a8a2d125e9e062f9b4071cf4741c/recipe/meta.yaml#L13-L17

Following [upstream](https://github.com/plasma-umass/scalene/blob/2814d8c11b28ba480988eedbf1617af7a925c174/setup.py#L231), this should be:

```yaml
build: 
  skip: true  # [py<38] 
  number: 1
  entry_points:
    - scalene = scalene.__main__:main
  script: {{ PYTHON }} -m pip install . -vv 
```

***xref:*** https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#python-entry-points
